### ISSUE TITLE
Coordinate System

### ISSUE THREAD

**Issue by rtpavlovsk21** [ros-drivers/velodyne#113]
In your readme can you make a warning for swapping coordinate systems to the ROS standard? For example if the system is mounted any other way than vertical the [ROS conventions](http://www.ros.org/reps/rep-0103.html) are not consistent and differ from the [VLP16 manual](http://velodynelidar.com/docs/manuals/VLP-16%20User%20Manual%20and%20Programming%20Guide%2063-9243%20Rev%20A.pdf).

**Comment by jack-oquin** [comment]
Velodyne coordinates differ from various ROS standards no matter how the device is mounted.

The documentation does mention this, but not in any README. Which one do you think should explain it?

**Comment by chukcha2** [comment]
In case this is useful to put into some README or manual:

Frame of reference for the velodyne, as set up by the velodyne_driver, axes shown below:
X → Forward
Y → Left
Z → Up

![image](https://cloud.githubusercontent.com/assets/8009504/21912348/55e68444-d8f3-11e6-8708-158913270e01.png)

However, the original velodyne coordinate frame as described by the VLP-16 manual is shown below:

![image](https://cloud.githubusercontent.com/assets/8009504/21912361/6bf50094-d8f3-11e6-987a-cdabd5f1567a.png)

**Comment by jack-oquin** [comment]
Would some definition of the "device frame of reference" be useful [here](http://wiki.ros.org/velodyne_pointcloud)?

If you think so, feel free to add it, perhaps in a new section following the overview.

**Comment by matheusns** [comment]
I have a VLP16 and I'll have to use it in a vertical way. How can I change the coordinates to fix it?

**Comment by jack-oquin** [comment]
You just need to define the [ROS TF tree](http://wiki.ros.org/tf2) correctly. The device frame is called ``velodyne``, or whatever you specified for the ``frame_id`` parameter.

**Comment by matheusns** [comment]
@jack-oquin  Could you give an example for us, please? Because I've not gotten the expected result. I want to change the axes and use the Velodyne in a vertical way.

**Comment by jlblancoc** [comment]
Hi,

You will probably get a better and faster answer by asking in
http://answers.ros.org because your doubt is quite general and is not
directly related to this package.

Best,


El 30 ene. 2017 6:33 PM, "matheusns" <notifications@github.com> escribió:

@jack-oquin <https://github.com/jack-oquin> Could you give an example for
us, please? Because I've not gotten the expected result. I want to change
the axes and use the Velodyne in a vertical way.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/ros-drivers/velodyne/issues/113#issuecomment-276129652>,
or mute the thread

**Comment by jack-oquin** [comment]
I agree with @jlblancoc that this is a general ROS coordinate transforms question, not directly related to the Velodyne at all.

Please ask your question on http://answers.ros.org with tags for ``tf``, ``tf2`` and ``velodyne``.
