### ISSUE TITLE
Velodyne wants to contribute fixes and new sensors files to this repository

### ISSUE THREAD

**Issue by mparkin** [ros-drivers/velodyne#141]
Can the repo maintainer respond to me to co ordinate this?

Thanks

**Comment by JWhitleyAStuff** [comment]
I just replied to your email regarding this. Please submit a pull request for any changes you wish to add. Note that I likely won't pull in any significant rewrites to the driver at this point since it is fairly stable and ROS 1 now has a limited lifespan given the release of ROS2. However, bug fixes and minor feature additions are always welcome.
