### ISSUE TITLE
Flickering of Velodyne Points

### ISSUE THREAD

**Issue by ptiwari0664** [ros-drivers/velodyne#163]
# ISSUE 
When I run 
* **roslaunch velodyne_pointcloud 32e_points.launch** With the parameter **rpm = 600**, the obtained velodyne_points does not flicker in rviz. However, with **1200 rpm**, velodyne_points flickers a lot.

# Parameters 
 * /velodyne_nodelet_manager_cloud/max_range: 130.0
 * /velodyne_nodelet_manager_cloud/min_range: 1.1
 * /velodyne_nodelet_manager_driver/device_ip: 
 * /velodyne_nodelet_manager_driver/frame_id: velodyne
 * /velodyne_nodelet_manager_driver/model: 32E
 * /velodyne_nodelet_manager_driver/pcap: 
 * /velodyne_nodelet_manager_driver/port: 2368
 * /velodyne_nodelet_manager_driver/read_fast: False
 * /velodyne_nodelet_manager_driver/read_once: False
 * /velodyne_nodelet_manager_driver/repeat_delay: 0.0
 * /velodyne_nodelet_manager_driver/rpm: 1200
 * /velodyne_nodelet_manager_laserscan/resolution: 0.007
 * /velodyne_nodelet_manager_laserscan/ring: -1

Is it a issue due to the high rotation of velodyne or something else ???
Thanks in advance !!!

**Comment by JWhitleyAStuff** [comment]
Did you modify the actual rotation rate in the Velodyne web interface first? This parameter doesn't actually modify the configuration of the Velodyne itself, it's meant to match the settings that you set in the web interface. Not sure it's even capable of 1200 RPM. Also, keep in mind that the rotation rate doesn't affect the sample rate - the lazer is still pulsing at 10Hz regardless of the rotation rate.

**Comment by ptiwari0664** [comment]
Hello Mr. Whitley,
Yes, I have modified in web interface as well. However I prefer ROS packages. 
Have checked the HDL-32 user manual, where the capabilities were cross-checked and the manual says that the RPM can be set in the multiple of 60 (Max 1200).
I have cross-checked the publishing /velodyne_points publishing rate, and it is ~20Hz (19.8 - 20.0). Therefore, I believe that the HDL-32 is pulsing at 20Hz. 

These points flicker in rviz.

**Comment by JWhitleyAStuff** [comment]
I have added issue #199 to be more clear in the documentation about the capabilities of the driver. For the time being, please be aware that the following will cause inconsistencies in the production of the point cloud in ROS:

 - Changing the RPM in the launch file to a value that does not match the sensor.
 - Changing the RPM on the sensor to a value that does not match the launch file.
 - Enabling dual-return mode.

**Comment by samkys** [comment]
Is this completely solved? Reason I ask we are seeing similar flicker even if both values match. This is visible with the vlp-16 -32 that we have. This does not show up if you visualize using Velodyne's tool. From what I can tell it is due to the fact that the actual RPM fluctuates slightly and the driver is polling data at the exact set value that it was set at. If you watch the actual RPM of the sensor it fluctuates a little say 599-602. See attached image you can see where the point cloud data has points held over.

To see this just record a bagfile with the Velodyne being moved on a vehicle or manually
![Screenshot from 2019-03-27 11-45-45](https://user-images.githubusercontent.com/20194956/55090768-0fa7b680-5086-11e9-92a3-1a5c4e577c6f.png)
, then play the bagfile back with -r 0.1 it is very visible as that's how I got this screenshot.

**Comment by JWhitleyAStuff** [comment]
@samkys - This is a known issue with the driver. See Jack's comment here: https://github.com/ros-drivers/velodyne/issues/33#issuecomment-58757287 If you would like to submit a PR to attempt to correct it, I'd be happy to review.

**Comment by samkys** [comment]
Ahhh, thanks didn't see #33. Not certain when I can get to it but will see what I can do. Thanks for the update!
