### ISSUE TITLE
VLP16 incorrect timestamp

### ISSUE THREAD

**Issue by ogail** [ros-drivers/velodyne#218]
Hi,
We had a problem with VLP16 providing incorrect timestamps. Looking further in `rawdata.cc`, in `unpack` method we do following
```
const unsigned int* timestamp_since_last_hour = reinterpret_cast<const unsigned int*>(&pkt.data[1200]);
double packet_timestamp = static_cast<double>(*timestamp_since_last_hour) * 1e-6;
```

My expectation that the `packet_timestamp` should be always between `0` and `3600` seconds inclusive (as the timestamp is from last hour based on VLP-16 User Manual 63-9243 Rev. D). However I get this series of data for `packet_timestamp`
```
3599.98
3599.99
3600
48
3600.01
3600.02
3600.03
3600.05
3600.06
```
I wonder how come the timestamp started to be greater than an hour (i.e. `3600.01`).

**Comment by JWhitleyAStuff** [comment]
I have not seen this issue and I believe you are correct about the timestamp_since_last_hour's expected values. Could you provide a more comprehensive log using the latest version of the driver? A PR was merged that allows using the actual packet time from the sensor to pass through instead of using an interpolated ROS time - please enable this feature with the `gps_time` parameter and see if the values change. I suspect that this is related to the time interpolation.

**Comment by JWhitleyAStuff** [comment]
@ogail - Ping.

**Comment by ogail** [comment]
We didn’t get a chance yet to update the driver, once happens will let you know

**Comment by nisailhan** [comment]
> We didn’t get a chance yet to update the driver, once happens will let you know

Is there any update?
