### ISSUE TITLE
How to transfer the .pack format into txt

### ISSUE THREAD

**Issue by killyseason** [ros-drivers/velodyne#229]
I have some datasets in the format of .pack ,each contains one frame scan ladar data,and I want to use the velodyne package to transfer the .pack format into .txt format and show the xyz coordinate.What can I do, I'm totally a freshman to the velodyne,What command line do I need to enter?
Thanks!

**Comment by JWhitleyAStuff** [comment]
The Velodyne driver does not currently support this format. If you build a converter to combine the .pack files and produce a .pcap file (not an easy task) then you could replay the .pcap file through the driver, record the output as a rosbag and then use something like https://github.com/AtsushiSakai/rosbag_to_csv to convert the output to human-readable. Otherwise, I'm not sure I can help with that format.
