### ISSUE TITLE
Proposed addition of GPS and IMU data

### ISSUE THREAD

**Issue by ibaranov-cp** [ros-drivers/velodyne#24]
Hey,

I was wondering why no one ever added in the GPS and IMU data.
I am going to be working on this, and might ask for a merger later.

**Comment by SISegwayRmp** [comment]
I'll put up an IMU driver for the HDL-32E soon, we used it to gather IMU data for online 3D mapping but gave up the 32 for a few 16's. I have quite a bit of inertial estimation experience and I must warn that the 32E inertial sensors are not temperature or bias corrected; they are good enough for gross correction since they are frame aligned with laser data and the accs are redundant. 

More useful is the GPS NTPD server I used that aligned the laser firing data with our odometry data on the embedded side, it eliminates ghosts at high speed (>6m/s).  But since it is so tied into our embedded state estimate it'll probably be a while before I can come up with some way include that. I will include it with the Segway RMP V3 stack that we'll be releasing soon.

**Comment by jack-oquin** [comment]
Sounds great, thanks!

**Comment by ksatyaki** [comment]
Is there any update on this? Has the GPS been interfaced?

**Comment by ibaranov-cp** [comment]
We ended going with an external, higher quality data source anyway.
The onboard IMU and GPS re-boradcast is not great.
Possibly this is being eliminated in the newer small "puck" velodynes anyway.

**Comment by PatrickHussey** [comment]
Agreed we ended up standardizing on the VLP-16 which does not have the IMU data, we usually use a MicroStrain 3DM-GX3-35 (or 45) in conjunction with the Velodyne sensors. 

Like ibaranov-cp said, the Velodyne inertial sensors are not calibrated and the GPS re-broadcast is pretty limited. Go with a good calibrated inertial sensor and a GPS that doesn't get relayed by the Velodyne.

**Comment by va9abund** [comment]
Hello,

I'd like to ask you for hint, on the branch gps_imu there's interesting node velodyne_gps_imu, however there ain't any launch file inside. And rqt_graph shows nothing from pub/subscribers used in source files. Has anyone have done any tests of this? 

I've got VLP-16 and I'd like to improve SLAM-mapping using position from GPS.
As you can see from the image when I go and back it loses odometry and I end up with 2 different clouds. I will appreciate any help. 

![capture](https://user-images.githubusercontent.com/33001302/36140468-aa0009ec-10a1-11e8-9922-c3cace0bf934.PNG)

**Comment by JWhitleyWork** [comment]
GPS data was added some time ago. IMU data does not seem to be wanted. Closing.

**Comment by Interaze** [comment]
Hi @JWhitleyWork. Did you have a reference to the GPS data included? I could see the timestamps, but I wasn't sure where the actual GPS positioning would be
