### ISSUE TITLE
How to calibrate the extrinsic parameters between two Lidars ?

### ISSUE THREAD

**Issue by MaxChanger** [ros-drivers/velodyne#241]
Hello, I want to use two lidars on a mobile platform at the same time. 
Now, according to the issue tutorial #108 , I successfully connect two lidars on a laptop computer. I can get the data of two lidars at the same time. Next, I need to know the relative position of two lidars, that is, the R T matrix.
I wonder if this package provides a method for calibrating the extrinsic parameters between two lidars, or is there a recommended calibration method.
Thank you!

![image](https://user-images.githubusercontent.com/35401968/57572343-5ccfc400-744b-11e9-9d06-2cc563c15d88.png)

**Comment by JWhitleyAStuff** [comment]
@MaxChanger - This package does not currently provide such a utility. In order to calibrate the offset, you should create two transforms - one from Velodyne1's frame to the vehicle frame (usually base_link) and another from Velodyne2's frame to the vehicle frame. After that, our usual calibration procedure looks like this:

1. Choose one of the Velodynes as your "primary" and measure the X/Y/Z and R/P/Y as accurately as possible on that lidar, using laser levels, if available.
2. Set up an object with a decent-sized lidar cross-section directly in front of the vehicle along the X axis. Again, use a laser level, if available, to make sure it is perfectly aligned with the central (X) axis of the vehicle.
3. With the vehicle on flat ground and using a side-on view in RViz (facing the Y+ direction with Z up) and the global frame set to the vehicle frame, adjust the transform from Velodyne1 to the vehicle frame until the lidar ground points are parallel with and touching the ground-plane grid in RViz.
4. Using a top-down view in RViz (facing Z- with X up) with the global frame set to the vehicle frame, adjust the Velodyne1 to vehicle transform until the lidar cross-section of the object in front of the vehicle is centered along the Y=0 line of the grid.
5. At this point, Velodyne1 should be correctly aligned. Set up two objects at different distances from the vehicle and use their lidar cross-sections to adjust the Velodyne2-to-vehicle-frame transform until the cross-sections overlap as close as possible.

This is our method but there are others. However, this package does not offer an "automated" method for the extrinsic calibration.
