### ISSUE TITLE
Release for Indigo

### ISSUE THREAD

**Issue by adasta** [ros-drivers/velodyne#29]
The repository compiles and runs in Indigo.  What needs to be done to set up the deb release for Indigo?

**Comment by jack-oquin** [comment]
Despite the many good suggestions made here, I don't see any compelling reason to change the current parameters (and I personally rather like them).

Since the discussion has lapsed, I am closing the issue now. If anyone feels strongly enough to continue the discussion, please do re-open this issue. Thanks to all who participated.
