### ISSUE TITLE
packet ending bytes format inquiry

### ISSUE THREAD

**Issue by prclibo** [ros-drivers/velodyne#30]
Hi,
I find [this](https://github.com/ros-drivers/velodyne/blob/000bbd70df3590607cf0358b9d8c1aebf5cd7d64/velodyne_pointcloud/include/velodyne_pointcloud/rawdata.h#L103) packet format seems not consistent with the format from either HDL-64E S2 or HDL-32E manuals, where the ending 6 bytes in a packet is define as:

> The 6 extra bytes at the end of the HDL-32E data packet are used to report GPS timing. For every packet, the last 6 bytes are formatted as follows:
> 4 bytes: 32 bit unsigned integer time stamp. This value represents microseconds from the top of the hour to the first laser firing in the packet.
> 2 bytes: blank

So just curious why they are different.

**Comment by jack-oquin** [comment]
Also, the GPS is optional on some device models. When missing, the time stamp field contains microseconds since power-up using the device's internal clock. That is not particularly useful to publish.

**Comment by jack-oquin** [comment]
I am closing this now, since the misleading HDL-64E comments have been removed from the header, and we have no clear proposal for how to support the full time stamp it across the various device models.

There is a more concrete proposal to publish GPS time based on the port 8308 position packets provided by some device models.

If you believe there is a good way forward using the time stamps, please re-open this issue.
