### ISSUE TITLE
question about organized point cloud

### ISSUE THREAD

**Issue by Zhang-Qinghui** [ros-drivers/velodyne#313]
**Please complete the following information:**
 - OS and Version: Ubuntu 16.04
 - ROS Version: Kinetic
 - Built from Source 
 - Version:  commit 7208295

**Describe the bug**
hi, organized clouds could  be accessed in a matrix fashion and I have tried, but I have one thing don't understand. Does the point under the same index number in the ordered point cloud of different frames come from the same position in the actual space?
![2019-11-12 18-49-00屏幕截图](https://user-images.githubusercontent.com/49428118/68666563-1afd1300-057f-11ea-9814-a50513a60652.png)
the picture shows the point at Column 8 line 180 of  pointclouds from the different frames,and the velodyne is fixed, the environment is constant. But the point data is different. Shouldn't the data be the same？ thank you in advance.

**Expected behavior**
I want some explanation about the problem.

**Comment by JWhitleyAStuff** [comment]
@Zhang-Qinghui - There is an inherent problem with the current driver's implementation regarding the size of a "scan" - see https://github.com/ros-drivers/velodyne/pull/285 for explanation. The organized point cloud feature can only organize the data that it is given and, since the driver is inconsistent on the size of a "scan," the precise location of a point within a scan is currently non-deterministic. If you would like to work on this PR to fix this issue, help would be welcome.

**Comment by Zhang-Qinghui** [comment]
Thanks for your reply. I think it's because the rotation speed of the radar is unstable.This is a hardware problem.
