### ISSUE TITLE
Creating Pointclouds with constant amounts of data 

### ISSUE THREAD

**Issue by JuicyJay** [ros-drivers/velodyne#365]
For my specific use case, I would need pointclouds with a constant amount of data (so for each cloud a constant number of pints, constant width in msg). More accurately: I would always need all returns from all firings in inclination and all azimuths, so that in the end the number of measurements only depends on resolution settings.

I was running an older version and recently found the commit #360 (thanks a lot for this work!) and tested commit Add invalid points in organized cloud #360 in hope that this will exactly solve my problem because it looked very promising. Unfortunately, looking at the output using rostopic echo /velodyne_points | head, I still see varying pointcloud widths.

Can anyone point me to a possible solution?
My next step will now be to try in gazebo with the simulation first to get this straight. But it would definitely be nicer to also be able to do it with real data. 

I appreciate any comments and help! 
**THANK YOU :-)**

**Comment by luis-robotic** [comment]
Hi! @jasminziegler 

Thank you for sharing your experience and for testing the changes in commit #360. I have a very similar requirement for pointclouds with a constant amount of data (constant width and inclusion of all firings/returns, even invalid ones). I was wondering if you were able to resolve this issue or find a workaround since your original post.

If you managed to achieve this, could you share how you addressed the varying pointcloud widths? Did you modify the driver further, or were there specific configurations or parameter tweaks that helped?

Any insights would be greatly appreciated, especially as I'm also looking for a solution for real data processing and ensuring consistent pointcloud structure.
