### ISSUE TITLE
how to convert velodyne_msgs/VelodyneScan into sensor_msgs/PointCloud2 with XYZIRT ?

### ISSUE THREAD

**Issue by mujiubai** [ros-drivers/velodyne#460]
**Please complete the following information:**
 - OS and Version: [Ubuntu 16.04]
 - ROS Version: [Kinetic]
 - Built from Source or Downloaded from Official Repository:
 - Version: [1.6.1]

**Describe the bug**
I want to convert velodyne_msgs/VelodyneScan into sensor_msgs/PointCloud2, and compile the v1.6.1 driver.
I use the convert node to convert the msg, but the result is XYZIR, it's no time.
How can I get the XYZIRT ? thanks a lot

**To Reproduce**
1. compile driver
2. run roscore
3. rosrun nodelet nodelet standalone velodyne_pointcloud/CloudNodelet  _calibration:="/home/enwu/catkin_ws/src/velodyne/velodyne_pointcloud/params/VLP16db.yaml" 
4. rosbag play  a.bag

**Comment by JWhitleyWork** [comment]
@mujiubai Unfortunately, the Kinetic version of the driver does not support this field and Kinetic is no longer supported so a Pull Request to add this feature would not be reviewed or accepted. Please use a newer version of ROS which is still supported such as Melodic, Noetic, or Foxy from ROS2. Otherwise, you will need to make your own fork and add the feature yourself.
